import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/zk-proofs', 'concepts/midnight-blockchain'],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/installation', 'getting-started/quickstart'],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/document-scanning',
        'features/face-verification',
        'features/proof-generation',
        'features/midnight-verification',
        'features/custom-checks',
      ],
    },
    'architecture',
    'usage-guide',
    {
      type: 'category',
      label: 'API / SDK',
      items: ['api/sdk-overview', 'api/methods'],
    },
    'use-cases',
    'security',
    'faq',
    'contribute',
    'license',
  ],
};

export default sidebars;
